# -*- coding: utf-8 -*-
"""PythonPrac_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bf9jLL2Uli03IvWHIo9SA-OpeATytNkr

Achintya Kamath

Roll Number - R030

MBA Tech Artificial Intelligence

Batch -  B2

Experiment 5- Dictionary and Math module

Aim:

A. Dictionary
1. To write a Python program to create the given dictionary
2. To write a Python program to print keys and values of the dictionary
using dict.keys(), dict.items()
3. To write a Python program to store the frequency of words in the list
and storing it in a dictionary
4. To write a Python program to map two lists into a dictionary
"""

a_dictionary = {
  'Manufacturer-': 'Porsche',
  'Model-': '911 (997) GT3',
  'Year-': 2009 
}
print ("The dictionary is : " + str(a_dictionary))

print ("\nDictionary key-values are : ", end="\n")
for i in a_dictionary :
    print(i, a_dictionary[i], end="\n")

test_string=input("Enter string:")
list_1=[]
list_1=test_string.split()
wordfreq=[list_1.count(p) for p in list_1]
another_dictionary = dict(zip(list_1,wordfreq))

print("\nThe characters of the string are put in a dictionary like so,\n", another_dictionary)

thing_1 = [ "993 Turbo Cabriolet-", "991 Club Coupe-", "964 Turbo Cabriolet-", "993 Speedster-" ]
thing_2 = [ 14, 13, 8, 2 ]

rare_911 = dict(zip(thing_1, thing_2))

print("\nSome of the rarest Porsche 911's ever made are displayed below,\n",
      rare_911)
print("\nProperly,\n")

for p in rare_911 :
    print(p, rare_911[p], end="\n")

"""**Conclusion:** Dictionary is an interesting data type in python that can make an unordered collection of anything basically. It assigns each item a key, which is basically a value. This makes it a nice way to display various things. """